services:
  # Service PHP Apache
  apache:
    build:
      context: ./php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html

  # Service MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mabase
      MYSQL_USER: mabase
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  # Service PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - mysql

  # Service Mailhog
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"